CREATE SEQUENCE ORG_UNIT_SEQ;

CREATE SEQUENCE ORG_BUSINESS_AREA_SEQ;

CREATE SEQUENCE ORG_SUB_BUSINESS_AREA_SEQ;

CREATE SEQUENCE JURISDICTION_SEQ;

CREATE SEQUENCE SERVICE_SEQ;

create sequence SERVICE_TO_CCD_SERVICE_ASSOC_SEQ;

commit ;
