CREATE SEQUENCE ORG_UNIT_SEQ;

CREATE SEQUENCE ORG_BUSINESS_AREA_SEQ;

CREATE SEQUENCE ORG_SUB_BUSINESS_AREA_SEQ;

CREATE SEQUENCE JURISDICTION_SEQ;

create sequence SERVICE_TO_CCD_CASE_TYPE_ASSOC_SEQ;

commit ;
