jdbc-batch-size: 10
start-route: direct:LRD
lrd-route-task: lrdRouteTask
routes-to-execute: lrd-ccd-casetype-load
route:
  lrd-ccd-casetype-load:
    id: lrd-ccd-casetype-load
    file-name: OrgServiceCCDMapping.csv
    table-name: service_to_ccd_case_type_assoc
    truncate-sql:
      sql:TRUNCATE service_to_ccd_case_type_assoc RESTART identity?dataSource=#dataSource
    insert-sql:
      sql:INSERT INTO service_to_ccd_case_type_assoc (service_code, ccd_service_name, ccd_case_type, created_date)
      VALUES (:#service_code,:#ccd_service_name,:#ccd_case_type, NOW() AT TIME ZONE 'utc')
      ON CONFLICT (service_code, ccd_case_type) DO NOTHING ?dataSource=#dataSource
    blob-path:
      azure-storage-blob://${azure.storage.account-name}/lrd-ref-data?credentials=#credsreg&operation=uploadBlockBlob&blobName=OrgServiceCCDMapping.csv
    processor-class: serviceToCcdCaseTypeProcessor
    mapper-class: serviceToCcdCaseTypeMapper
    csv-binder-object: serviceToCcdCaseType

